# Generated by Django 3.1.5 on 2021-01-25 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaMarki', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Marki',
            },
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaSamochodu', models.CharField(max_length=50)),
                ('opis', models.TextField(blank=True)),
                ('rokProdukcji', models.DecimalField(decimal_places=0, max_digits=99999)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=99999)),
                ('kolor', models.CharField(max_length=50)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marka.brand')),
            ],
            options={
                'verbose_name': 'Samochod',
                'verbose_name_plural': 'Samochody',
            },
        ),
    ]
