# Generated by Django 3.1.5 on 2021-01-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marka', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='opis',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='nazwaMarki',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='marka',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='kolor',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='opis',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='nazwaSamochodu',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='cena',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='rokProdukcji',
            new_name='production_year',
        ),
    ]
