# Generated by Django 3.1.5 on 2021-01-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marka', '0004_auto_20210126_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('name',)},
        ),
    ]
