# Generated by Django 3.1.5 on 2021-01-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaMarki', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
            ],
        ),
    ]
