# Generated by Django 3.1.5 on 2021-01-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='samochod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaMarki', models.CharField(max_length=100)),
                ('nazwaSamochodu', models.CharField(max_length=50)),
                ('opis', models.TextField(blank=True)),
                ('rokProdukcji', models.DecimalField(decimal_places=0, max_digits=99999)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=99999)),
                ('kolor', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Samochod',
                'verbose_name_plural': 'Samochody',
            },
        ),
        migrations.AlterModelOptions(
            name='marka',
            options={'verbose_name': 'Marka', 'verbose_name_plural': 'Marki'},
        ),
    ]
