# Generated by Django 3.1.5 on 2021-01-25 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marka', '0002_auto_20210125_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samochod',
            name='nazwaMarki',
        ),
        migrations.AddField(
            model_name='samochod',
            name='marka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marka.marka'),
        ),
    ]
